<a href="https://colab.research.google.com/github/aman-5137/half_plasma/blob/main/_9_CrossValidation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv("/content/heart_disease.csv", na_values='?').dropna()
df['target'] = (df['num'] > 0).astype(int)

X = df.drop(columns=['num', 'target'])
y = df['target']
print("rows :", len(X), 'features : ', X.shape[1])


rows : 297 features :  13


In [2]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [3]:
# SVM
from sklearn.svm import SVC

svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.6666666666666666

In [4]:
# Random Forest
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.85

In [7]:
# K-Fold cross validation

from sklearn.model_selection import KFold

kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [8]:
data = [1,2,3,4,5,6,7,8]
for train_index, test_index in kf.split(data):
  print(train_index, test_index)

[3 4 5 6 7] [0 1 2]
[0 1 2 6 7] [3 4 5]
[0 1 2 3 4 5] [6 7]


In [9]:
svm_score=[]
rf_score = []


for train_index, test_index in kf.split(X, y):
  X_train, X_test = X.iloc[train_index], X.iloc[test_index]
  y_train, y_test = y.iloc[train_index], y.iloc[test_index]

  svm = svm = SVC()
  svm.fit(X_train, y_train)
  svm_score.append(svm.score(X_test, y_test))


  rf = RandomForestClassifier()
  rf.fit(X_train, y_train)
  rf_score.append(rf.score(X_test, y_test))


print(svm_score)
print(rf_score)

[0.6161616161616161, 0.6565656565656566, 0.6060606060606061]
[0.8484848484848485, 0.8282828282828283, 0.797979797979798]


In [10]:
np.mean(svm_score)

np.float64(0.6262626262626263)

In [11]:
np.mean(rf_score)

np.float64(0.8249158249158249)

In [14]:
# CROSS VALIDATION METHOD
from sklearn.model_selection import cross_val_score

cross_val_score(SVC(), X, y, cv=3)

array([0.58585859, 0.66666667, 0.60606061])

In [15]:
cross_val_score(RandomForestClassifier(), X, y, cv=3)

array([0.83838384, 0.77777778, 0.78787879])

In [17]:
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=3)

number = [1,2,3,4,5,6,7,8,9]
labels=  [0,0,0,1,0,0,1,0,1]

for train_index, test_index in skf.split(number, labels):
  print(train_index, test_index)

[2 4 5 6 7 8] [0 1 3]
[0 1 3 5 7 8] [2 4 6]
[0 1 2 3 4 6] [5 7 8]


In [21]:
# Here we used the stratify method that helps in selecting equal amount of input and test data
cross_val_score(RandomForestClassifier(), X, y, cv=skf)

array([0.86868687, 0.80808081, 0.75757576])